branches:
  only:
    - master
    - /^8\.x.*/
    - /^7\.x.*/
    - /^6\.x.*/
language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_install:
  - composer self-update
install:
  - composer global require pdrakeweb/drupal-module-lint:7.*@dev
script:
  - $HOME/.composer/vendor/bin/dmlint
