<?php

/**
 * @file
 * Module file for tracelytics module
 */

/**
 * Implements hook_init().
 *
 * Include tracelytics RUM javascripts if enabled.
 */
function tracelytics_init() {
  if (variable_get('tracelytics_rum', FALSE)) {
    drupal_add_js(oboe_get_rum_header(FALSE),
      array(
        'type' => 'inline',
        'scope' => 'header',
        'group' => JS_THEME,
        'every_page' => TRUE,
        'weight' => 1000,
        'preprocess' => FALSE,
      )
    );
    drupal_add_js(oboe_get_rum_footer(FALSE),
      array(
        'type' => 'inline',
        'scope' => 'footer',
        'group' => JS_THEME,
        'every_page' => TRUE,
        'weight' => 1000,
        'preprocess' => FALSE,
      )
    );
  }
}

/**
 * Implements hook_menu().
 */
function tracelytics_menu() {
  $items['admin/config/system/tracelytics'] = array(
    'title' => 'Tracelytics',
    'description' => 'Configure the settings used for tracelytics (oboe).',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tracelytics_admin_settings'),
    'access arguments' => array('administer tracelytics'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_perm().
 */
function tracelytics_permission() {
  return array(
    'administer tracelytics' => array(
      'title' => t('Administer tracelytics'),
      'description' => t('Configure settings for the tracelytics module.'),
    ),
  );
}

/**
 * Implements hook_admin_settings().
 *
 * Provide administrative options to enable/disable tracelytics functionality.
 */
function tracelytics_admin_settings() {
  global $conf;

  if (!(function_exists('oboe_log'))) {
    drupal_set_message(t('Required Oboe PHP extension is not installed.'), 'error');
  }

  if (empty($conf['tracelytics_fail_silently'])) {
    drupal_set_message(t('The tracelytics module is not configured to fail silently.  Removal of the php-oboe extension may cause fatal errors.'), 'warning');
  }

  if (!($tracelytics_layers_modules = module_exists('tracelytics_early') && module_exists('tracelytics_late'))) {
    drupal_set_message(t('tracelytics_early and tracelytics_late must be installed in order to track layers.'), 'warning');
  }

  if (variable_get('tracelytics_partition_drush_traffic', FALSE) || variable_get('tracelytics_track_drush_commands', FALSE)) {
    drupal_set_message(t('oboe.tracing must be configured to "always" for PHP CLI in order to trace drush commands.'), 'notice');
  }

  $drupal_http_request_function = variable_get('drupal_http_request_function', 'tracelytics_drupal_http_request');
  if ($drupal_http_request_function !== 'tracelytics_drupal_http_request') {
    drupal_set_message(t('Overriding the drupal_http_request_function variable is required in order to trace drupal_http_request calls. The variable has already been overridden (@function), possibly by another module.', array('@function' => $drupal_http_request_function)), 'warning');
  }

  $form = array();
  $form['tracelytics_partition_traffic'] = array(
    '#type' => 'checkbox',
    '#title' => t('Partition traffic'),
    '#description' => t('Enable partitioning of traffic into drush, cron, anonymous and authenticated.'),
    '#default_value' => variable_get('tracelytics_partition_traffic', FALSE),
    '#disabled' => !(function_exists('oboe_log')),
  );
  $form['tracelytics_rum'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track RUM'),
    '#description' => t('Enable tracking of Real User Monitoring data via javascript.'),
    '#default_value' => variable_get('tracelytics_rum', FALSE),
    '#disabled' => !(function_exists('oboe_get_rum_header')),
  );
  $form['tracelytics_track_menu'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track active menu items'),
    '#description' => t('Enable tracking of the active menu item and first argument as Controller/Action.'),
    '#default_value' => variable_get('tracelytics_track_menu', FALSE),
    '#disabled' => !(function_exists('oboe_log') && function_exists('menu_get_item')),
  );
  $form['tracelytics_log_errors'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track watchdog'),
    '#description' => t('Enable tracking of watchdog entries of WATCHDOG_WARNING or greater severity as errors.'),
    '#default_value' => variable_get('tracelytics_log_errors', FALSE),
    '#disabled' => !(function_exists('oboe_log')),
  );
  $form['tracelytics_layers'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track layers'),
    '#description' => t('Enable tracking of Drupal layers via hooks.'),
    '#default_value' => variable_get('tracelytics_layers', FALSE),
    '#disabled' => !$tracelytics_layers_modules,
  );
  $form['tracelytics_drupal_http_request'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track drupal_http_request'),
    '#description' => t('Enable tracking of drupal_http_request calls.  This requires Drupal 7.22 or above (see http://drupal.org/drupal-7.22-release-notes).'),
    '#default_value' => ('tracelytics_drupal_http_request' === variable_get('drupal_http_request_function', FALSE)),
    '#disabled' => version_compare(VERSION, '7.22', '<') || $drupal_http_request_function !== 'tracelytics_drupal_http_request',
  );
  $form['tracelytics_drush'] = array(
    '#type' => 'fieldset',
    '#title' => 'Drush integration',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['tracelytics_drush']['tracelytics_partition_drush_traffic'] = array(
    '#type' => 'checkbox',
    '#title' => t('Partition traffic'),
    '#description' => t('Enable partitioning of traffic into drush, cron, anonymous and authenticated.'),
    '#default_value' => variable_get('tracelytics_partition_drush_traffic', FALSE),
  );
  $form['tracelytics_drush']['tracelytics_track_drush_commands'] = array(
    '#type' => 'checkbox',
    '#title' => t('Track active menu items'),
    '#description' => t('Enable tracking of the active menu item and first argument as Controller/Action.'),
    '#default_value' => variable_get('tracelytics_track_drush_commands', FALSE),
  );
  $form['#submit'][] = 'tracelytics_admin_settings_form_submit';
  return system_settings_form($form);
}

/**
 * Implements hook_form_submit().
 *
 */
function tracelytics_admin_settings_form_submit($form, &$form_state) {
  $drupal_http_request_function = variable_get('drupal_http_request_function');
  $enable = $form_state['values']['tracelytics_drupal_http_request'];
  if (empty($drupal_http_request_function) && $enable) {
    variable_set('drupal_http_request_function', 'tracelytics_drupal_http_request');
  } else if ($drupal_http_request_function === 'tracelytics_drupal_http_request' && !$enable) {
    variable_del('drupal_http_request_function');
  }
  unset($form_state['values']['tracelytics_drupal_http_request']);
}

/**
 * Implements hook_watchdog().
 *
 * Record errors to tracelytics.
 */
function tracelytics_watchdog($log_entry) {
  if (variable_get('tracelytics_log_errors', FALSE)
      && $log_entry['severity'] <= WATCHDOG_WARNING
      && $log_entry['type'] != 'php') {
    $message = filter_xss(is_null($log_entry['variables']) ? $log_entry['message'] : strtr($log_entry['message'], $log_entry['variables']));
    oboe_log('info', array('ErrorClass' => $log_entry['type'], 'ErrorMsg' => $message));
  }
}

/**
 * Implements hook_exit().
 *
 * Record tracelytics traffic partitioning and controller.
 */
function tracelytics_exit() {
  global $user, $_tracelytics_partition;

  // Partition traffic.
  if (variable_get('tracelytics_partition_traffic', FALSE)) {
    if (!empty($_tracelytics_partition)) {
      oboe_log('info', array('Partition' => $tracelytics_partition));
    }
    else {
      switch ($user->uid) {
        case 1:
          oboe_log('info', array('Partition' => 'Admin'));
          break;

        case 0:
          oboe_log('info', array('Partition' => 'Anonymous'));
          break;

        default:
          oboe_log('info', array('Partition' => 'Authenticated'));
          break;
      }
    }
  }

  // Track active menu item.
  if (function_exists('menu_get_item')
      && variable_get('tracelytics_track_menu', FALSE)
      && $router_item = menu_get_item()) {
    tracelytics_set_controller(
      array(
        'Controller' => $router_item['page_callback'],
        'Action' => (isset($router_item['page_arguments'][0]) ? tracelytics_get_action($router_item['page_arguments'][0]) : 'NULL'),
      )
    );
  }

  $controller = tracelytics_set_controller(NULL, FALSE, TRUE);
  if (!empty($controller)) {
    oboe_log('info', $controller);
  }
}

/**
 * Set the controller to be reported to tracelytics.
 *
 * @param array $controller
 *   The controller array to be reported to tracelytics.
 * @param bool $override
 *   Flag to indicate whether the passed controller should override previously
 *   set controller array.
 * @param bool $alter
 *   Flag to indicate whether to call hook_alter on the controller array.
 *
 * @return array
 *   The controller array to be reported to tracelytics.
 */
function tracelytics_set_controller($controller = NULL, $override = FALSE, $alter = FALSE) {
  static $tracelytics_controller = array();
  if (!empty($controller) && ($override || empty($tracelytics_controller))) {
    $tracelytics_controller = $controller;
  }
  if (function_exists('drupal_alter') && $alter) {
    drupal_alter('tracelytics_controller', $tracelytics_controller);
  }
  return $tracelytics_controller;
}

/**
 * Implements hook_cron().
 *
 * Record tracelytics traffic partitioning and controller within cron.
 */
function tracelytics_cron() {
  // Partition cron traffic.
  if (variable_get('tracelytics_partition_traffic', FALSE)) {
    oboe_log('info', array('Partition' => 'Cron'));
  }

  // Track active menu item.
  if (variable_get('tracelytics_track_menu', FALSE)) {
    oboe_log('info',
      array(
        'Controller' => 'cron',
        'Action' => NULL,
      )
    );
  }
}

/**
 * Get an action string from an unknown argument type.
 *
 * @param mixed $argument
 *   Argument variable as passed to menu callback.
 *
 * @return string
 *   Description (or string conversion) of $argument.
 */
function tracelytics_get_action($argument) {
  switch (gettype($argument)) {
    case 'integer':
    case 'double':
    case 'boolean':
    case 'string':
      $action = (string) $argument;
      break;

    case 'array':
      $action = 'array';
      break;

    case 'object':
      if (!empty($argument->nid)) {
        $action = (!empty($argument->type) ? $argument->type . '_' : '') . 'node';
      }
      elseif (!empty($argument->uid)) {
        $action = 'user';
      }
      else {
        $action = get_class($argument);
      }
      break;

    case 'resource':
      $action = get_resource_type($argument);
      break;

    default:
      $action = NULL;
      break;
  }
  return $action;
}

/**
 * Set the tracelytics partition.
 *
 * @param string $partition
 *   Traffic partition name.
 */
function tracelytics_set_partition($partition) {
  global $_tracelytics_partition;
  $_tracelytics_partition = $partition;
}

/**
 * Wrap calls to drupal_http_request, permitting layer creation and full-stack application tracing.
 *
 * Minimum Drupal version is 7.22: http://drupal.org/drupal-7.22-release-notes
 *
 * @param $url
 *   A string containing a fully qualified URI.
 * @param array $options
 *   (optional) An array with options as per drupal_http_request().
 */
function tracelytics_drupal_http_request($url, array $options = array()) {
  global $conf;

  // Parse the URL for information about the query being made.
  $uri = parse_url($url);

  // Collect information about non-standard ports
  $remote_host = $uri['host'];
  $remote_host .= isset($uri['port']) && $uri['port'] != 80 ? ':' . $uri['port'] : '';

  // Collect fragments and querystrings
  $service_arg = $uri['path'];
  $service_arg .= isset($uri['fragment']) ? $uri['fragment'] : '';
  $service_arg .= isset($uri['query']) ? $uri['query'] : '';

  // Start the drupal_http_request layer (with a backtrace).
  oboe_log('drupal_http_request', 'entry', array(
    'IsService' => 'True',
    'RemoteProtocol' => $uri['scheme'],
    'RemoteController' => 'drupal_http_request',
    'RemoteHost' => $remote_host,
    'ServiceArg' => $service_arg,
  ), TRUE);

  // Set an X-Trace header.
  $options['headers']['X-Trace'] = oboe_get_context();

  // Allow drupal_http_request to temporarily bypass the override.
  unset($conf['drupal_http_request_function']);

  // Call drupal_http_request.
  $response = drupal_http_request($url, $options);

  // Put the override back in place.
  $conf['drupal_http_request_function'] = 'tracelytics_drupal_http_request';

  // Stop the drupal_http_request layer.
  oboe_log('drupal_http_request', 'exit', array('ResponseCode' => $response->code));

  return $response;
}

/**
 * In order to support configurations where the php-oboe extension may or may
 * not be available during a given application execution, such as during the
 * execution of a drush command, on a singler server in a cluster or on a non-
 * production environment, the following code will optionally define the
 * missing functions as empty functions provided the tracelytics_fail_silently
 * configuration setting is not empty.
 */
global $conf;
if (!empty($conf['tracelytics_fail_silently'])) {
  if (!function_exists('oboe_log')) {
    // These functions intentionally left empty.
    function oboe_log() {}
    function oboe_get_rum_header() {}
    function oboe_get_rum_footer() {}
  }
}
