<?php

/**
 * @file
 * Module file for traceview_early module
 */

/**
 * Implements hook_boot().
 */
function traceview_early_boot() {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_hook_boot', 'entry', array());
  }
}

/**
 * Implements hook_init().
 */
function traceview_early_init() {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_hook_init', 'entry', array());
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param array $form
 * @param array $form_state
 * @param string $form_id
 */
function traceview_early_form_alter(&$form, &$form_state, $form_id) {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_hook_form_alter', 'entry', array('Form-ID' => $form_id));
  }
}

/**
 * Implements hook_views_pre_view().
 *
 * @param object $view
 * @param string $display_id
 * @param array $args
 */
function traceview_early_views_pre_view(&$view, &$display_id, &$args) {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_views', 'entry', array('View-Name' => $view->name, 'View-Display-ID' => $display_id));
  }
}

/**
 * Implements hook_panels_pre_render().
 *
 * @param object $display
 * @param object $renderer
 */
function traceview_early_panels_pre_render($display, $renderer) {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_panels', 'entry', array('Panel-Renderer' => $display->renderer, 'Panel-Layout' => $display->layout));
  }
}

/**
 * Implements hook_nodeapi().
 *
 * @param object $node
 * @param string $op
 * @param array $a3
 * @param array $a4
 */
function traceview_early_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'load' && variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_hook_node_load', 'entry', array('Node-NID' => $node->nid, 'Node-Type' => $node->type));
  }
}

/**
 * Implements hook_watchdog().
 *
 * @param array $log_entry
 */
function traceview_early_watchdog($log_entry) {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_hook_watchdog', 'entry', array());
  }
}

/**
 * Implements hook_footer().
 */
function traceview_early_footer($main = 0) {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_hook_footer', 'entry', array());
  }
}

/**
 * Implements hook_exit().
 */
function traceview_early_exit() {
  if (variable_get('traceview_layers', FALSE)) {
    traceview_oboe_log('drupal_hook_exit', 'entry', array());
  }
}
